# worfklow name (override name defined on the RO-Crate metadata)
name: "Sort and change case"
# worfklow visibility
public: true

# Issue Checker Settings
issues:
  # Enable/Disable issue checker
  # The list of issue types can be found @ <LIFEMONITOR_API_URL>/workflows/issues
  # (e.g., https://api.lifemonitor.eu/workflows/issues)
  check: true
  # csv of issues to check (all included by default)
  # include: [repo_layout.MissingROCrateFile, experimental.OutdatedROCrateFile, lm.MissingLMConfigFile, lm.InvalidConfigFile, repo_layout.RepositoryNotInitialised, metadata.MissingWorkflowName, repo_layout.MissingWorkflowFile, repo_layout.MissingROCrateWorkflowFile]
  # csv of issues to ignore (none ignored by default)
  # exclude: [repo_layout.MissingROCrateFile, experimental.OutdatedROCrateFile, lm.MissingLMConfigFile, lm.InvalidConfigFile, repo_layout.RepositoryNotInitialised, metadata.MissingWorkflowName, repo_layout.MissingWorkflowFile, repo_layout.MissingROCrateWorkflowFile]


# Github Integration Settings
push:
  branches:
    - name: 'main'
      update_registries: []
  tags:
    - name: "*.*.*"
      update_registries: ["wfhubdev"]
